site_name: OMAR Web Services
pages:
- Home: 'index.md'
- Install Guide:
  - 'Common Install': 'install-guide/common.md'
  - 'OMAR/O2 UI' : 'install-guide/omar-app.md'
  - 'WMTS Service': 'install-guide/wmts-app.md'
  - 'WMS Service': 'install-guide/wms-app.md'
  - 'WFS Service': 'install-guide/wfs-app.md'
  - 'Swipe Service': 'install-guide/swipe-app.md'
  - 'Stager Service': 'install-guide/stager-app.md'
  - 'Super Overlay Service': 'install-guide/superoverlay-app.md'
  - 'JPIP Service': 'install-guide/jpip-app.md'
  - 'JPIP Streaming Service': 'install-guide/jpip-server.md'
