version: '2'
services:
  o2-base:
    build: ./o2-base
    image: rbt/o2-base
  wmts:
    environment: 
      DBHOST: wmtsdb
      DBPORT: 5432
      DBNAME: omar_prod
      DBUSER: wmts
      DBPASS: abc123
      WFSSERVER: http://otd-omar-single.rbtcloud.com
      WFSPORT: 80
      WMSSERVER: http://otd-omar-single.rbtcloud.com
      WMSPORT: 80
    build: ./wmts-app
    ports:
      - "8080:8080"
    image: rbt/wmts
    depends_on:
      - o2-base
      - wmtsdb
  wmtsdb:
    environment:
      POSTGRES_PASSWORD: abc123
      POSTGRES_USER: o2
      POSTGRES_DB: omar_prod
    image: postgres:latest

